# Generated by Django 5.2.17 on 2026-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=500)),
                ("source_date", models.DateField(blank=True, null=True)),
                ("checksum", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                ("row_count", models.PositiveIntegerField()),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PostOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pincode", models.CharField(db_index=True, max_length=6)),
                ("office_name", models.CharField(max_length=200)),
                ("district", models.CharField(db_index=True, max_length=200)),
                ("state", models.CharField(db_index=True, max_length=200)),
                ("circle", models.CharField(max_length=200)),
                ("region", models.CharField(blank=True, max_length=200)),
                ("division", models.CharField(max_length=200)),
                ("office_type", models.CharField(max_length=30)),
                ("delivery", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["pincode", "state", "district", "office_name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pincode", "state", "district", "office_name"),
                        name="unique_post_office",
                    )
                ],
            },
        ),
    ]
