# Generated by Django 5.2.17 on 2026-09-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postoffice",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postoffice",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
