# Generated by Django 5.2.17 on 2026-09-26 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postal", "0002_postoffice_latitude_postoffice_longitude"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="postoffice",
            name="unique_post_office",
        ),
    ]
