# Generated by Django 5.2.17 on 2026-09-26 07:49

from collections import Counter

from django.db import migrations


def count_repeated_identities(apps, schema_editor):
    """Record, for an existing directory, how many offices it lists more than once."""
    Dataset = apps.get_model("postal", "Dataset")
    PostOffice = apps.get_model("postal", "PostOffice")
    db = schema_editor.connection.alias
    fields = ("pincode", "state", "district", "office_name")
    # The same identity rule as the importer: case-insensitive, compared in Python.
    identities = Counter(
        tuple(value.casefold() for value in row)
        for row in PostOffice.objects.using(db).values_list(*fields).iterator()
    )
    repeated = sum(count > 1 for count in identities.values())
    Dataset.objects.using(db).filter(pk=1).update(repeated_identity_count=repeated)


class Migration(migrations.Migration):
    dependencies = [
        ("postal", "0005_dataset_repeated_identity_count"),
    ]

    operations = [
        migrations.RunPython(count_repeated_identities, migrations.RunPython.noop),
    ]
